"""empty message

Revision ID: 758c4b8037f6
Revises: 
Create Date: 2017-06-25 12:21:16.119894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758c4b8037f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('favourite', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dinner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_ingredient',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('food_id', 'ingredient_id')
    )
    op.create_table('starter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lunch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('need_starter', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('related_dinner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['related_dinner_id'], ['dinner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('lunch_id', sa.Integer(), nullable=True),
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.Column('starter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dinner_id'], ['dinner.id'], ),
    sa.ForeignKeyConstraint(['lunch_id'], ['lunch.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['starter_id'], ['starter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_menu')
    op.drop_table('lunch')
    op.drop_table('starter')
    op.drop_table('food_ingredient')
    op.drop_table('dinner')
    op.drop_table('product')
    op.drop_table('menu')
    op.drop_table('ingredient')
    op.drop_table('food')
    # ### end Alembic commands ###
